Fix initial migations for MySQL.
InnoDB/utf8 has a limit of 255 chars for unique fields.
Error: "1071 - Specified key was too long; max key length is 767 bytes"
This happens because 3 chars * 255 bytes = 765

Replaced the max_length in migrations, there is no need to truncate
existing beta installations on PostgreSQL.